name: Generate Feed

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to allow committing files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important to allow token use for push

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python generate_feed.py

      - name: Commit and push updated files
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add feed.xml articles.json
          git diff --cached --quiet || git commit -m "Update feed"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push
